language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://sarajimenez.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "Stj6ePKYmSAyRcPAC6F8joNB+AdRSFVSAsrUgo5M8NBeIExv47GnZDUK3fquqtEo+lxmcP/KLpXz7lwHdb2vkDFJ8BI5y3duTw7vcc8/fd4GIy0xeaNP2qzdJZAQK3j0tfx6FlI0TA0sbBGL/egUvd9HjbYFw6+iummOialK6iNSh5/dH6KE7SsEhbyh5kffc7LxUJdf73V7wcEV7dkwx5a/UDz4f6QHZnxpbt97EDkwAKd+/ee/VnQWTj61Ecxx7F/N7NzcRYZJkWcD40ByTLUCDrQ/z0BajRPzdV3OznEnvO26S9sNlHO6ZoKllW9uUing24ViLdXQXcfOqFhXOVGf8Iff+BSrHeNeSWWpyqfeLN/B2q4eJ4WCGqR5YbuUwHnTcYss5K3CtIfs/bcLlX0iZfqFqZIuMq8WCFd+PQtjL4jVPUONy0kmJ60SlOjF3Twr5MGlFSaOaddmyJjHCnfRA9X+gOZSinqNQoAf170uOgsqHL/16ZOllXvtEWvOg2+z85goKyva+3hRyiBwu2Ms+Y1Om4WN4zdsE07XI4YTZ2NxZBT/AWhm6VHzj4acoGQaEpyhFh9OgG/hjYbksE0QeHg+92IaQZIrTag6SCVnbE4274y6cF82ybXgBZfb5fQjgXUgFrMbnKmGXoYFhgYLJ4uxQr3l763q3ZX5bvw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
